### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jokereven** [jokereven/MyFlow#1]
- [x] https://youtu.be/NYdJyFsCHd8 通过合约创建一个链上钱包;

- [x] https://youtu.be/Eti_a8ALzsM 通过cex dex套利;

- [x] https://github.com/stars/acheong08/lists/awesome-chatgpt some chatgpt demo;

- [x] https://github.com/smile201708/freemint-monitor-main freemint, 有意思的是有个闹钟提醒, 不知道是什么东西, 我记得是, 调用一个mp3文件;

- [x] ``https://github.com/search?q=chatgpt+assistant&type=Repositories 主要是我希望做一个 ai 助手解放我的双手;
> https://github.com/gia-guar/JARVIS-ChatGPT
> https://github.com/aneeshkp246/Jarvis_AI
> https://github.com/alondmnt/joplin-plugin-jarvis
> https://github.com/GauravSingh9356/J.A.R.V.I.S
> https://github.com/sitek94/jarvis-gpt-chrome-extension
> https://github.com/evildevill/Jarvis
> https://github.com/Emi1699/Jarvis
> https://github.com/11CyBeRGh0sT11/Speech-Recognized-AI
> https://github.com/bharathmuppa/jarvis
> https://github.com/Ghostasky/Jarvis
> 找到一些jarvis的仓库有几个不错的之后试试; 运行了一个效果还不错, 在wsl试了一下看来是不行可能是因为wsl无法调用麦克风的问题;
 
- [x] https://github.com/yubing744/trading-gpt 结合chatgpt的交易机器人;

- [x] https://github.com/liang3472/freemint-bot freemint discord bot;

- [x] https://github.com/SnakeHacker/QA-Snake 基于多搜索引擎和深度学习技术的自动问答;

- [x] https://github.com/RimoChan/sese-engine 一个py写的清理级搜索引擎;
> 之后可以尝试自己写一个搜索引擎; 

- [x] https://github.com/nektos/act 本地运行的github actions;

- [x] https://github.com/junegunn/fzf fzf 是一个通用的命令行模糊查找器;

- [x] https://vim0.com/post/neovim/ 使用 neovim 作为PDE(个性化开发环境); > 还得好久之后.

- [x] https://github.com/5m477/Ethereum-Portfolio-Tracker 通过 newPendingTransactions 监听地址;
> 大概可以作为erc20token的监听器;

- [x] https://github.com/Albert-W/ether_crawler 获取eth上待处理的交易;

- [x] https://github.com/brendan-mccaffrey/eth-gas-tracker eth gas 和 eth price 的关系;

- [x] https://github.com/h2kh/wallet_analysis eth 地址研究;

- [x] https://github.com/Dpm99/Ethereum-Analysis 也是一个eth 地址研究, 但是好像是大量数据研究 Analysis of the full set of transactions which have occurred on the Ethereum network from the first transactions in August 2015 until June 2019. Created several Map/Reduce or Spark programs to perform multiple types of computation;

- [x] https://github.com/michelemarzollo/cil_sentimental_sourdough 可能是研究 eth 相关信息在 twitter 上的情况, Sentiment Analysis on a Twitter dataset for the course Computational Intelligence Lab 2020 at ETH;

- [x] https://github.com/andrewre23/SocialCryptoModeling 分析 eth 和 btc 的走势. Using social network analysis to predict price movements of Bitcoin (BTC) and Ethereum (ETH);

- [x] https://github.com/nirvansarju/Crypto-Prediction-ML 通过机器学习预测eth价格;

- [x] https://github.com/molu0219/NFT-Mint-Wallet-Analysis  关于一个nft集合的mint分析;

- [x] https://github.com/ra1ngts/projects 感觉挺多的. 货币分析、信用钱包、密码生成器、密码管理器、电报机器人;

- [x] https://link3.to/settings link3 个人页面 可能需要 10$ 左右, 现在感觉有点贵, 等赚到钱在搞. 

- [x] https://twitter.com/junjie9021/status/1640750238079258624 空投猎人分析

- [x] https://twitter.com/magnoli95821980/status/1642108572460027906 百倍币

- [x] https://twitter.com/ashu_mest/status/1642722609803714560 mest waitlist

- [x] https://twitter.com/iamyourchaos/status/1643052337555181569 质押 goerli test network eth

- [x] https://twitter.com/xiaxiaoyubing/status/1651218841517584391 一些ai的产品

- [x] https://twitter.com/Ximu_simo/status/1647233779470323713 追番解决方案
> https://www.himiku.com/archives/auto-bangumi.html https://reorx.com/blog/track-and-download-shows-automatically-with-sonarr https://sinon.top/sinon-bangumi-list

- [x] 动漫视频搜索器, 也可以叫聚合器, http://www.yinghuacd.com/show/3849.html (樱花动漫)

- [x] https://twitter.com/0xLaughing/status/1628764380585426951 《让我看看你的 NFT，我就能告诉你它将表现如何：多模态表征学习用于 NFT 售价预测》

- [x] https://mirror.xyz/0xC6D545FA2a9738933e7Fb40ac7024FbD951bAe0A/a_P1RLBn8TSnECBwKnNsjPz5XpdfTC2Hq8jx4WUaeLE https://mirror.xyz/0xC6D545FA2a9738933e7Fb40ac7024FbD951bAe0A/YN4ELgCvPa8meD0Zdgkkgf0SiJc9HMadONnQxipf3Zw 撸毛

- [x] https://space.bilibili.com/394425489/channel/collectiondetail?sid=707231 neovim 学习
 
- [x] 使用飞书开发类似tg机器人

- [x] https://github.com/EstrellaXD/Auto_Bangumi AutoBangumi - 全自动追番工具，节约时间创造价值

- [x] https://github.com/dair-ai/Prompt-Engineering-Guide 🐙 Guides, papers, lecture, notebooks and resources for prompt engineering

- [x] https://github.com/GruDev325/AutoTradingBot Automated cryptocurrency trading bot

- [x] https://github.com/chrism2671/PyTrendFollow PyTrendFollow - systematic futures trading using trend following

- [x] https://github.com/depp57/muskbot Simple bot that buy a crypto when a followed twitter account tweet something positive about that coin.

- [x] https://twitter.com/JimmyZengX/with_replies 分析twitter某个用户的关注与推文.

- [ ] https://github.com/JetCyC/web3_script_tutorial , https://github.com/junjie9021/simple-airdrop-demo/blob/main/zksync/demo.py py撸毛 

- [x] https://skybyte.me/55.html 自己本地训练chatgpt4

- [x] https://docs.alchemy.com/docs/how-to-create-a-whale-alert-discord-bot 编写一个自己的discord机器人对钱包地址进行监控.

- [x] https://pixso.cn/designskills/10-ai-paint-builders/ https://github.com/AUTOMATIC1111/stable-diffusion-webui https://stablediffusionweb.com/ https://github.com/alembics/disco-diffusion ai 图片生成

- [ ] 今晚又写了一个小玩具～, 工作流同样是：chatgpt 写前端 -> go 完成逻辑层 -> vercel 部署(结合 AIGC+serverless 后，toy proj 整个只需要一两个小时), [http://encrypt.devs.wtf](https://t.co/5qcnjjuUoe), 背景是某些人希望在墙内冲塔但老被封号，因此希望可以有一种墙内可用的高效加密通讯手段，因此我写了这么一个小玩意～, 伪加密对话.

- [x] new bing on obsidian 写接入 bard or new bing 到 obsidian 应为 chatgpt 的 api 之后可能也会到期之后可能就用不了了, 得提前找好替代平2333.

- [x] https://twitter.com/XMRer/status/1647399157907492864 twitter @IFTTT 工作流
> 太贵了, 放弃.

- [x] https://twitter.com/9hills/status/1651790309381271553 obsidian 同步方案
> 个人感觉和使用坚果云没太大的区别.

- [x] https://twitter.com/bearboxcn/status/1643627450121723904 openai 不需要私钥调用的方法

- [ ] 使用 poetry 将整个项目(py项目)进行重新的管理.

- [x] vscode url to params 插件完成

- [x] https://twitter.com/CoinAxiom/status/1653586302015770624 推送指定用户推文;

- [x] https://twitter.com/0x14os/status/1628704949004820483 监控机器人

- [x] https://surmon.me/article/163 https://www.blueskyxn.com/202202/5755.html#%E5%89%8D%E8%A8%80 github Sponsors 开通

- [x] https://surmon.me/sponsor#wechat-pay 个人赞助页, 使用wise开通 github sponsor.

- [x] https://bytetalk.fm/posts/episode-6/ # [跟 Anthony Fu 聊聊全职开源和他的故事](https://bytetalk.fm/posts/episode-6/)

- [x] jokereven.cc 域名注册, 把antfu的博客抄过来.

- [x] https://hyoban.cc https://github.com/hyoban/blog https://hyoban.cc/post/3a8e9bfe-9280-47c7-b9ff-3a39e00ba9f2 react 最新技术栈.
> 抄一个博客.

- [x] https://hyoban.xlog.app/feishu-webhook-ai 飞书机器人

- [ ] ai 生成手画风格的图片
> https://experiments.withgoogle.com/cartoonify 找到了,

- [x] https://pro.opensea.io/collection/nakamigone/analytics 分析卖的手法.

- [x] https://github.com/search?q=sui+token+language%3AMove&type=repositories&l=Move https://github.com/kirill-m21/fungible_token sui token

- [x] 关于win_rate_nftgo项目过段时间得整理一下有点乱, 可以把整个项目做成像dogfind那样, 通过token分析也可以做成那样, 之后还是得通过分析log日志来分析, 那样肯定要看起来牛逼一点;

- [x] 有钱之后再去买一些稳定币;

- [x] https://twitter.com/Bitturing/status/1653794317415350273 Bark 音频 AI王炸

- [x] https://twitter.com/GPTDAOCN/status/1653904052898648066 用开源软件在本地实现私有数据检索问答的教程.

- [x] https://pro.nansen.ai 下面有个GM Digest - Market News 说不定之后可以研究一下;

- [x] https://github.com/Jaewan-Yun/QuantNN 经过训练的编码器-解码器神经网络模型可以预测移动平均 ETH-USD 价格的未来差异对数.

- [x] github sponsers 验证

- [x] 土狗 token 日志获取器, https://github.com/search?q=eth+logs&type=repositories&p=10 https://github.com/soos3d/test-rpc-getLogs-limits

- [x] 国内Onekey Card快速开通ChatGPT Plus教程 https://juejin.cn/post/7223343320298324029

- [x] https://github.com/AzizFacilex/ZizouEthereumCracker Crack Ethereum wallets by finding their Mnemonics, using 100% of CPU, logging to Blockchain Contract for use on multiple Nodes.

- [x] https://github.com/n0thing2speak/MeituanRedenvelope https://github.com/zjing125/meituan-shenquan 我fork了一下感觉大概率是不能用了过几天自己写一个 美团自动领劵. https://github.com/zjing125/actions-mtz-coupons 用这个解决了这个办法;

- [x] https://github.com/vv314/actions-mtz-coupons/issues 感觉美团领的优有点小, 过几天造个轮子;

- [x] https://twitter.com/LinqinEth/status/1654748797526999041 小狐狸空投反思;

- [x] https://github.com/hengxuZ/discord-chat-tools discord 自动肝白

- [x] discord 监控, https://github.com/littleleoman/FOMO-Twitter-Monitor https://github.com/bcloutier412/Discord-Bot-Monitor-RP https://github.com/Ramzi-Sah/discordMonitorChannel-selfBot  https://github.com/skateboard/discord-monitor 写差不多了, 明天优化一下加上chatgpt.

- [x] twitter 自动发推.

- [x] https://github.com/f/awesome-chatgpt-prompts chatpg promot more will

- [x] https://github.com/yuk7/ArchWSL 完美的arch wsl

- [x] https://docs.opensea.io/reference/api-overview opensea的apikey终于开放了,看来是格局打开了.可以把之前没没法写的东西继续开始写.

- [x] 今天用autocode整了一下 chatgpt in discord, 但是不知道为什么就用不了, 细节, all in ai bot;

- [x] 不知道为什么就是感觉特别乱;

- [x] [vv314/actions-mtz-coupons: 以自动化的方式领取外卖红包。 (github.com)](https://github.com/vv314/actions-mtz-coupons) 一个美团自动领劵的, 看来不错;

- [x] https://github.com/imartinez/privateGPT Interact privately with your documents using the power of GPT, 100% privately, no data leaks.

- [x] https://github.com/LoveGlaze/COC-Tool 部落冲突 coc 脚本.

- [x] https://github.com/anywhere2go/auto_player https://github.com/hanmin0822/RaphaelScriptHelper https://github.com/search?q=游戏脚本&type=repositories 游戏挂机脚本.

- [x] followmint py 程序的依赖问题, 降低py版本试试;

- [x] ai 生成 音乐;

- [x] https://www.youtube.com/watch?v=_cofqkSS00A ai 替换音乐的音色;

- [x] 搞了半天github申请没过, github copilot 学生认证;
> 已经在淘宝搞好了.

- [x] https://github.com/TabbyML/tabby https://github.com/fauxpilot/fauxpilot Self-hosted AI coding assistant. An opensource / on-prem alternative to GitHub Copilot. 暂时使用不了;

- [x] https://github.com/zyddnys/manga-image-translator/blob/main/README_CN.md 高亮半天验证还是没过, 不过找到个不错的东西; 在淘宝整了一个;

- [x] https://github.com/jingfelix/BiliFM https://github.com/jokereven/bilibili-save-nodejs 获取bilibili音频文件.

- [x] https://github.com/mirawara/transcriber https://github.com/Disha-Bhatti/Audio2Text-Recognition https://github.com/maranemil/python_audio2text 音频to文件.

- [x] [微笑]直接搭建自己的直播间：live.hsslive.cn

- [x] https://juejin.cn/post/7215842530838085692?share_token=5b9d657e-e2f1-45d0-bae0-d62b1f0ca0e2#heading-5 使用 ffmpeg 推流到bilibil

- [x] 【【NovelAI】ChatGPT+TTS+SoVITS+Python批量原创小说短视频】 https://www.bilibili.com/video/BV1Pk4y1n7PE/

- [x] 【自制会「鞠躬」的小灯（STM8）】 https://www.bilibili.com/video/BV1ak4y1j7uY/

- [x] https://github.com/jokereven/MyKeymap 原理学习;

- [x] https://github.com/chatanywhere/GPT_API_free free chatgpt api

- [x] 【three.js 当夏天遇上菊次郎...怀念那个盛夏】 https://www.bilibili.com/video/BV1Eg4y1E7tm https://github.com/mudroljub/create-3d-worlds

- [x] Vscode Setting 配置和分享;

- [x] https://githubnext.com github copilot x 的使用, 先继续等;

- [x] chatgpt agent discord 优化;

- [x] https://docs.rsshub.app rsshub;

- [x] No-code AI workflow https://github.com/AndersonBY/vector-vein

- [x] https://github.com/Dapp-Learning-DAO/Dapp-Learning/blob/main/README-CN.md dapp 开发

- [x] https://github.com/autoai-org/AID 机器学习

- [x] https://github.com/fastai/fastbook 深度学习

- [x] https://github.com/mnielsen/neural-networks-and-deep-learning Code samples for my book "Neural Networks and Deep Learning"

- [x] https://github.com/AlwinBrauns/ETHCardNFT Learning project, React with TypeScript, ethersjs, ETH, Blockchain, Solidity, ERC721

- [x] https://github.com/ABCDEcapital/Understanding-Ethereum-Go-version Understanding Ethereum: Go-Ethereum Code Analysis｜理解以太坊: Go-Ethereum 源码剖析[^go-ethereum] 

- [x] https://github.com/DessertHeart/Dive-Into-Blockchain 旨在交流学习区块链技术，记录智能合约开发应用与相关安全练习的仓库🚀

- [x] https://github.com/AmazingAng/WTF-Solidity soldity 学习

- [x] https://github.com/vercel/swr SWR is a React Hooks library for data fetching.

- [x] https://www.solidjs.com learn solidjs

- [x] https://twitter.com/kuangshenbtc/status/1648351946439536641 一个web3邮箱项目 [@ethermail_io](https://twitter.com/ethermail_io) ,融资250万, 注册绑定邮箱拿250颗 [$EMC](https://twitter.com/search?q=%24EMC&src=cashtag_click) 代币, 以前出过个视频, 最近他们参加黑客松, 再推一把.

- [x] https://github.com/Blockchain-zju/blockchainer-roadmap 区块链 roadmap

- [x] 使用 Wallet-Monitor(tg) 以及 Zerion DeBank 对地址进行监控, 使用Aptoide安装手机app.

- [x] 搞一个新的blog, 收sponser.
> https://afdian.net/a/jokereven 爱发电;
> https://www.buymeacoffee.com 需要国外卡, 暂时没搞;
> https://github.com/sponsors/ddiu8081 github sponsors;
> https://ko-fi.com/Manage ko-fi
> https://surmon.me/sponsor#wechat-pay 个人赞助页面;
> https://github.com/zhyd1997/sponsor web3 赞助
> max space: https://mx-space.js.org 看了一下好像必须得部署到服务器.

- [x] https://mirror.xyz/3344521.eth/ab6XPBUh0AWuUSprCK3gg5rpvLiErSSx45WAuZHAXLM web3 任务平台;
> auto in https://galxe.com

- [x] https://cook.aiurs.co https://cook.yunyoujun.cn how to cook.

- [x] diy 电动滑板.
> 暂时放弃.

- [x] 这里总结了 NFT 攻击有关的手法，大多都是各种骗、各种钓，然后是智能合约漏洞、交易市场漏洞等。挺好的总结： https://twitter.com/evilcos/status/1668184308451008512

- [x] scan token eth address to mongodb.

- [x] clash 网络问题, wsl 用一段时间之后 网络就不太好了.
 
- [x] twitter 关注部分推送，可能会使用 rsshub.
> 这里是使用 https://feedly.com/i/my 来解决这个问题的.
