### ISSUE TITLE
New TODO

### ISSUE THREAD

**Issue by jokereven** [jokereven/MyFlow#2]
- [ ] https://github.com/search?q=chatgpt+assistant&type=Repositories 主要是我希望做一个 ai 助手解放我的双手;
> https://github.com/gia-guar/JARVIS-ChatGPT
> https://github.com/aneeshkp246/Jarvis_AI
> https://github.com/alondmnt/joplin-plugin-jarvis
> https://github.com/GauravSingh9356/J.A.R.V.I.S
> https://github.com/sitek94/jarvis-gpt-chrome-extension
> https://github.com/evildevill/Jarvis
> https://github.com/Emi1699/Jarvis
> https://github.com/11CyBeRGh0sT11/Speech-Recognized-AI
> https://github.com/bharathmuppa/jarvis
> https://github.com/Ghostasky/Jarvis
> 找到一些jarvis的仓库有几个不错的之后试试; 运行了一个效果还不错, 在wsl试了一下看来是不行可能是因为wsl无法调用麦克风的问题;
> 这个东西可能还得托一段时间, 现在还没买麦克风, 或者说之后用我的 笔记本来录视频.

- [ ] https://github.com/ranckTony/freemint one self platform https://www.gem.xyz/mints;
> 一个 freemint 看板.

- [ ] https://github.com/fox493/findKing order by nft contract address to find dogking address(体验了一下, 感觉确实不错, 比我写的好过段时间研究一下.);

- [ ] 一些免费提供的api接口 https://github.com/MZCretin/RollToolsApi;
> https://github.com/ClassmateLin/proxy_pool go 爬虫提供api不知道原理是什么;

- [ ] https://github.com/darrylyeo/blockhead 一个区块链可视化看板;

- [ ] https://github.com/fox493/flash-bot-minter 批量mint xen;

- [ ] https://twitter.com/0xPzai/status/1640381383989399553 Crypto合规出金一图流率先奉上 Mirror文章明天奉上（主要是困了!🤣);
> https://mirror.xyz/pzai.eth/4P6ECZJ3-XZVG6N6dW_5zKT7QgQF2XuGD8rpyOJ8JvA 参考链接;

- [ ] https://www.bilibili.com/video/BV1MX4y1R7w3 【ChatGPT语音助手】语音交互 发短信 发邮件 控制程序 执行指令.
	- [ ] https://github.com/NeoTse/hal
	- [ ] https://github.com/nickbild/voice_chatgpt
	- [ ] https://github.com/LlmKira/Openaibot
	- [ ] https://github.com/hackingthemarkets/qa-assistant-eleven-labs-voice-cloning
	- [ ] https://www.bilibili.com/opus/791690720628965401
 
- [ ] https://github.com/zt0202002/MazeBot-for-Discord chatgpt discord bot with music

- [ ] https://github.com/moom825/Discord-RAT Discord Remote Administration Tool fully written in Python3

- [ ] 推送消息的解决办法.

- [ ] Automatically generate popular videos 自动生成热门视频: https://github.com/OmegaDING/AutoGenPopularVideo

- [ ] https://github.com/fighting41love/funNLP nlp 学习.

- [ ] https://github.com/HCLonely/awesome-bilibili-extra https://github.com/SocialSisterYi/bilibili-API-collect bilibili 的一些好玩的东西 Do Do Do!

- [ ] https://github.com/SkyFlap/Digital-Life-DL-B https://www.bilibili.com/opus/794751941342134274 https://github.com/THUDM/ChatGLM-6B 本次开源为DL-B，是一个基于ChatGLM、Wav2Lip、So-VITS组建的数字形象方案。可以在此基础之上增加其他组件达到数字生命的效果。This open source is DL-B, which is a digital image scheme based on ChatGLM, Wav2Lip and So-VITS. On this basis, other components can be added to achieve the effect of digital life.

- [ ] https://magetong.github.io/2021/12/13/Apps_for_Subtitle/ 字幕制作全流程可能用得到的各类软件

- [ ] https://github.com/SpeechColab/Leaderboard bilibili 视频字幕识别;

- [ ] https://sorcererxw.com/articles/vercel-go-microservice use vercel develop Go function;

- [ ] some autogpt tools
> https://github.com/richardyc/Chrome-GPT
> https://github.com/Hansimov/gpt-tools
> https://github.com/dheerajinampudi/ai-architect
> https://github.com/b8vipvip/AutoGPT
> https://github.com/alexfacehead/AutoGPTCommands
> https://github.com/alexdphan/babyagi-chroma-agent
> https://github.com/Significant-Gravitas/Auto-GPT

- [ ] https://github.com/hwholiday/learning_tools (微服务&DDD on Golang)

- [ ] arch linux
> ArchLinux KDE Plasma 自定义桌面。
官网:https://archlinux.org/
安装教程:https://arch-linux.osrc.com/
(Arch神教yyds!)

- [ ] archlinux 教程, 开发环境 + 良好的上网环境.

- [ ] eth nft 土狗看板.

- [ ] https://blog.rxliuli.com/p/1fcd1517c14c4e68b764d7e6df071805/ 在 react 中使用 mobx 接管所有状态

- [ ] https://github.com/AlwinBrauns/ETHCardNFT Learning project, React with TypeScript, ethersjs, ETH, Blockchain, Solidity, ERC721

- [ ] https://diygod.me/job rss3 job

- [ ] [https://dukedaily.github.io/solidity-exjpert](https://dukedaily.github.io/solidity-expert) soldity 学习

- [ ] https://study.163.com/course/introduction/1212937804.htm grpc(liwenzhou)
